const Checkpoint = [
  {
    desc: "欢迎来到FlexRabbit，让我们通过游戏来学习&nbsp;<label class=\"console-tags\">display:flex</label>&nbsp;的高效布局吧。请用&nbsp;<label class=\"console-tags\">justify-content</label>&nbsp;属性控制胡萝卜到右边的FlexRabbit上。这个属性定义了元素在水平上的对齐方式，并且接受以下几个参数：",
    tips: ["<label class=\"console-tags\">flex-start</label>&nbsp;元素和容器的左端对齐。",
      "<label class=\"console-tags\">flex-end</label>&nbsp;元素和容器的右端对齐。",
      "<label class=\"console-tags\">center</label>&nbsp;元素在容器内水平居中。",
      "<label class=\"console-tags\">space-between</label>&nbsp;元素之间的间隔都相等。",
      "<label class=\"console-tags\">space-around</label>&nbsp;元素两侧的间隔相等。"],
    container: ["justify-content:flex-end;"],
    carrot: ["#F9E784"],
    rabbit: ["#F9E784"],
    single: ["#"]
  },
  {
    desc: "再一次來使用&nbsp;<label class=\"console-tags\">justify-content</label>&nbsp;来捕获FlexRabbit吧。请记住&nbsp;<label class=\"console-tags\">justify-content</label>&nbsp;接受以下几个参数：",
    tips: ["<label class=\"console-tags\">flex-start</label>&nbsp;元素和容器的左端对齐。",
      "<label class=\"console-tags\">flex-end</label>&nbsp;元素和容器的右端对齐。",
      "<label class=\"console-tags\">center</label>&nbsp;元素在容器内水平居中。",
      "<label class=\"console-tags\">space-between</label>&nbsp;元素之间的间隔都相等。",
      "<label class=\"console-tags\">space-around</label>&nbsp;元素两侧的间隔相等。"],
    container: ["justify-content:center;"],
    carrot: ["#F9E784", "#ABE188"],
    rabbit: ["#F9E784", "#ABE188"],
    single: ["#", "#"]
  },
  {
    desc: "能否仅靠&nbsp;<label class=\"console-tags\">justify-content</label>&nbsp;来捕获三只FlexRabbit呢？如果你忘了&nbsp;<label class=\"console-tags\">justify-content</label>&nbsp;的可选值的话，可以回到上一关查看。",
    tips: ["为保证学习目的，请尽量避免去查看&nbsp;<label class=\"console-tags\">justify-content</label>&nbsp;的可选值喔"],
    container: ["justify-content:space-around;"],
    carrot: ["#F9E784", "#ABE188", "#F78E69"],
    rabbit: ["#F9E784", "#ABE188", "#F78E69"],
    single: ["#", "#", "#"]
  },
  {
    desc: "现在三只FlexRabbit都分散开来了，使得他们之间的间距变大了。使用&nbsp;<label class=\"console-tags\">justify-content</label>&nbsp;还能捕获成功吗？",
    tips: ["相信您到这一关已经基本记住可选值了"],
    container: ["justify-content:space-between;"],
    carrot: ["#F9E784", "#ABE188", "#F78E69"],
    rabbit: ["#F9E784", "#ABE188", "#F78E69"],
    single: ["#", "#", "#"]
  },
  {
    desc: "现在使用&nbsp;<label class=\"console-tags\">align-items</label>&nbsp;来捕获逃逸到底部的FlexRabbit。这个&nbsp;<label class=\"console-tags\">align-items</label>&nbsp;将会给您带来很大的帮助。",
    tips: ["<label class=\"console-tags\">flex-start</label>&nbsp;元素和容器的顶部对齐。",
      "<label class=\"console-tags\">flex-end</label>&nbsp;元素和容器的底部对齐。",
      "<label class=\"console-tags\">center</label>&nbsp;元素在容器内垂直居中。",
      "<label class=\"console-tags\">baseline</label>&nbsp;元素在容器内在容器基线位置对齐。",
      "<label class=\"console-tags\">stretch</label>&nbsp;元素被拉伸直至填满整个容器。"],
    container: ["align-items:flex-end;"],
    carrot: ["#F9E784", "#ABE188", "#F78E69"],
    rabbit: ["#F9E784", "#ABE188", "#F78E69"],
    single: ["#", "#", "#"]
  },
  {
    desc: "现在通过使用&nbsp;<label class=\"console-tags\">align-items</label>&nbsp;和&nbsp;<label class=\"console-tags\">justify-content</label>&nbsp;的组合尝试来捕获回到中心位置的FlexRabbit。",
    tips: ["请记住多动手才能记得牢固哦。", "同时也不要忘了代码的书写规范，分号是不能被省略的。"],
    container: ["justify-content:center;", "align-items:center;"],
    carrot: ["#F9E784"],
    rabbit: ["#F9E784"],
    single: ["#"]
  },
  {
    desc: "这次FlexRabbit们跑得更加分散了，胡萝卜距离FlexRabbit们有着充足的距离，快去使用&nbsp;<label class=\"console-tags\">align-items</label>&nbsp;和&nbsp;<label class=\"console-tags\">justify-content</label>&nbsp;的组合吧。",
    tips: ["属性可选值在前几关，真的要回去看吗？"],
    container: ["justify-content:space-around;", "align-items:flex-end;"],
    carrot: ["#F9E784", "#ABE188", "#F78E69"],
    rabbit: ["#F9E784", "#ABE188", "#F78E69"],
    single: ["#", "#", "#"]
  },
  {
    desc: "这次胡萝卜需要和FlexRabbit们保持一样的顺序，我们可以使用这个&nbsp;<label class=\"console-tags\">flex-direction</label>&nbsp;属性。这个CSS属性定义了元素在容器内摆放的位置，并且接受以下这些值：",
    tips: ["<label class=\"console-tags\">row</label>&nbsp;元素摆放位置的方向是水平的且与文字方向一致。",
      "<label class=\"console-tags\">row-reverse</label>&nbsp;元素摆放位置的方向和文字的方向相反。",
      "<label class=\"console-tags\">column</label>&nbsp;元素从上到下以垂直的方式摆放。",
      "<label class=\"console-tags\">column-reverse</label>&nbsp;元素从下到上以垂直的方式逆向摆放。"],
    container: ["flex-direction:row-reverse;"],
    carrot: ["#F78E69", "#ABE188", "#F9E784"],
    rabbit: ["#F78E69", "#ABE188", "#F9E784"],
    single: ["#", "#", "#"]
  },
  {
    desc: "使用&nbsp;<label class=\"console-tags\">flex-direction</label>&nbsp;属性，控制胡萝卜找到FlexRabbit的对应位置，请记住&nbsp;<label class=\"console-tags\">flex-direction</label>&nbsp;属性接受以下这些值：",
    tips: ["<label class=\"console-tags\">row</label>&nbsp;元素摆放位置的方向是水平的且与文字方向一致。",
      "<label class=\"console-tags\">row-reverse</label>&nbsp;元素摆放位置的方向和文字的方向相反。",
      "<label class=\"console-tags\">column</label>&nbsp;元素从上到下以垂直的方式摆放。",
      "<label class=\"console-tags\">column-reverse</label>&nbsp;元素从下到上以垂直的方式逆向摆放。"],
    container: ["flex-direction:column;"],
    carrot: ["#F9E784", "#ABE188", "#F78E69"],
    rabbit: ["#F9E784", "#ABE188", "#F78E69"],
    single: ["#", "#", "#"]
  },
  {
    desc: "控制胡萝卜抓到对应FlexRabbit，尽管看起来很近，但这需要用到&nbsp;<label class=\"console-tags\">flex-direction</label>&nbsp;和&nbsp;<label class=\"console-tags\">justify-content</label>&nbsp;来实现",
    tips: ["请注意，当你调转行或列的方向时，<label class=\"console-tags\">flex-start</label>&nbsp;和&nbsp;<label class=\"console-tags\">flex-end</label>&nbsp;对应的方向也被调换了。"],
    container: ["flex-direction:row-reverse;", "justify-content:flex-end;"],
    carrot: ["#F9E784", "#ABE188", "#F78E69"],
    rabbit: ["#F9E784", "#ABE188", "#F78E69"],
    single: ["#", "#", "#"]
  },
  {
    desc: "用&nbsp;<label class=\"console-tags\">flex-direction</label>&nbsp;和&nbsp;<label class=\"console-tags\">justify-content</label>&nbsp;来控制胡萝卜抓到对应FlexRabbit。注意当flex以行为方向时，<label class=\"console-tags\">justify-content</label>&nbsp;控制垂直对齐，<label class=\"console-tags\">align-items</label>&nbsp;控制水平对齐。",
    tips: ["本关没有更多提示了。"],
    container: ["flex-direction:column;", "justify-content:flex-end;"],
    carrot: ["#F9E784", "#ABE188", "#F78E69"],
    rabbit: ["#F9E784", "#ABE188", "#F78E69"],
    single: ["#", "#", "#"]
  },
  {
    desc: "还是用&nbsp;<label class=\"console-tags\">flex-direction</label>&nbsp;和&nbsp;<label class=\"console-tags\">justify-content</label>&nbsp;来控制胡萝卜抓到对应FlexRabbit。注意事项在上一关说过了，可不要忘了喔。",
    tips: ["本关没有更多提示了。"],
    container: ["flex-direction:column-reverse;", "justify-content:space-between;"],
    carrot: ["#F9E784", "#ABE188", "#F78E69"],
    rabbit: ["#F9E784", "#ABE188", "#F78E69"],
    single: ["#", "#", "#"]
  },
  {
    desc: "使用&nbsp;<label class=\"console-tags\">flex-direction</label>&nbsp;和&nbsp;<label class=\"console-tags\">justify-content</label>&nbsp;以及&nbsp;<label class=\"console-tags\">align-items</label>&nbsp;来控制胡萝卜抓到对应FlexRabbit。",
    tips: ["本关没有更多提示了。"],
    container: ["flex-direction:row-reverse;", "justify-content:center;", "align-items:flex-end;"],
    carrot: ["#F9E784", "#ABE188", "#F78E69"],
    rabbit: ["#F9E784", "#ABE188", "#F78E69"],
    single: ["#", "#", "#"]
  },
  {
    desc: "有时候仅仅调转列或行的方向是不足以控制胡萝卜抓到对应FlexRabbit的。我们可以设置单个元素的&nbsp;<label class=\"console-tags\">order</label>。虽然该元素的属性默认值为0，但是我们可以设置这个属性为正数或负数。",
    tips: ["使用&nbsp;<label class=\"console-tags\">order</label>&nbsp;来调整胡萝卜的顺序。"],
    container: [],
    carrot: ["#F9E784", "#ABE188", "#F78E69"],
    rabbit: ["#F9E784", "#ABE188", "#F78E69"],
    single: ["#", "order:1;", "#"]
  },
  {
    desc: "使用&nbsp;<label class=\"console-tags\">order</label>&nbsp;控制胡萝卜抓到对应的FlexRabbit！相信我，这会非常是简单的一件事。",
    tips: ["本关没有更多提示了。"],
    container: [],
    carrot: ["#F9E784", "#F9E784", "#F9E784", "#ABE188", "#F9E784"],
    rabbit: ["#F9E784", "#F9E784", "#F9E784", "#ABE188", "#F9E784"],
    single: ["#", "#", "#", "order:-1;", "#"]
  },
  {
    desc: "另一个你可以使用控制单个元素的属性是&nbsp;<label class=\"console-tags\">align-self</label>。这个属性接受和&nbsp;<label class=\"console-tags\">align-items</label>&nbsp;一样的值。",
    tips: ["本关没有更多提示了。"],
    container: [],
    carrot: ["#F9E784", "#F9E784", "#ABE188", "#F9E784", "#F9E784"],
    rabbit: ["#F9E784", "#F9E784", "#ABE188", "#F9E784", "#F9E784"],
    single: ["#", "#", "align-self:flex-end;", "#", "#"]
  },
  {
    desc: "使用&nbsp;<label class=\"console-tags\">order</label>&nbsp;和&nbsp;<label class=\"console-tags\">align-self</label>。来控制胡萝卜抓到对应的FlexRabbit。",
    tips: ["本关没有更多提示了。"],
    container: [],
    carrot: ["#ABE188", "#F9E784", "#ABE188", "#F9E784", "#F9E784"],
    rabbit: ["#ABE188", "#F9E784", "#ABE188", "#F9E784", "#F9E784"],
    single: ["align-self:flex-end;#order:1;", "#", "align-self:flex-end;#order:1;", "#", "#"]
  },
  {
    desc: "都挤到一行了！变形的胡萝卜可抓不了FlexRabbit！快使用&nbsp;<label class=\"console-tags\">flex-wrap</label>&nbsp;来调整一下胡萝卜。",
    tips: ["<label class=\"console-tags\">nowrap</label>&nbsp;所有元素都在一行。",
      "<label class=\"console-tags\">wrap</label>&nbsp;允许元素换行。",
      "<label class=\"console-tags\">wrap-reverse</label>&nbsp;元素会逆序换行。"],
    container: ["flex-wrap:wrap;"],
    carrot: ["#ABE188", "#F9E784", "#F9E784", "#F9E784", "#F9E784", "#F9E784", "#F78E69"],
    rabbit: ["#ABE188", "#F9E784", "#F9E784", "#F9E784", "#F9E784", "#F9E784", "#F78E69"],
    single: ["#", "#", "#", "#", "#", "#", "#"]
  },
  {
    desc: "控制胡萝卜排成三列，去捕获对应的FlexRabbit吧！可以使用&nbsp;<label class=\"console-tags\">flex-wrap</label>&nbsp;和&nbsp;<label class=\"console-tags\">flex-direction</label>&nbsp;的组合。",
    tips: ["<label class=\"console-tags\">nowrap</label>&nbsp;所有元素都在一行。",
      "<label class=\"console-tags\">wrap</label>&nbsp;允许元素换行。",
      "<label class=\"console-tags\">wrap-reverse</label>&nbsp;元素会逆序换行。"],
    container: ["flex-wrap:wrap;", "flex-direction:column;"],
    carrot: ["#F9E784", "#F9E784", "#F9E784", "#F9E784", "#F9E784",
      "#ABE188", "#ABE188", "#ABE188", "#ABE188", "#ABE188",
      "#F78E69", "#F78E69", "#F78E69", "#F78E69", "#F78E69"],
    rabbit: ["#F9E784", "#F9E784", "#F9E784", "#F9E784", "#F9E784",
      "#ABE188", "#ABE188", "#ABE188", "#ABE188", "#ABE188",
      "#F78E69", "#F78E69", "#F78E69", "#F78E69", "#F78E69"],
    single: ["#", "#", "#", "#", "#",
      "#", "#", "#", "#", "#",
      "#", "#", "#", "#", "#"]
  },
  {
    desc: "<label class=\"console-tags\">flex-wrap</label>&nbsp;和&nbsp;<label class=\"console-tags\">flex-direction</label>&nbsp;两个属性经常会在一起使用。所以Flex布局提供了一个缩写属性&nbsp;<label class=\"console-tags\">flex-flow</label>，这个属性接受两个属性的值，两个值中间以空格隔开。",
    tips: ["尝试使用&nbsp;<label class=\"console-tags\">flex-flow</label>&nbsp;来完成上一关的任务。"],
    container: ["flex-flow:column wrap;"],
    carrot: ["#F9E784", "#F9E784", "#F9E784", "#F9E784", "#F9E784",
      "#ABE188", "#ABE188", "#ABE188", "#ABE188", "#ABE188",
      "#F78E69", "#F78E69", "#F78E69", "#F78E69", "#F78E69"],
    rabbit: ["#F9E784", "#F9E784", "#F9E784", "#F9E784", "#F9E784",
      "#ABE188", "#ABE188", "#ABE188", "#ABE188", "#ABE188",
      "#F78E69", "#F78E69", "#F78E69", "#F78E69", "#F78E69"],
    single: ["#", "#", "#", "#", "#",
      "#", "#", "#", "#", "#",
      "#", "#", "#", "#", "#"]
  },
  {
    desc: "胡萝卜在广场到处都是，然而FlexRabbit都在顶部。你可以使用&nbsp;<label class=\"console-tags\">align-content</label>&nbsp;来决定行与行之间间隔多远。这个属性接受以下这些值。",
    tips: ["<label class=\"console-tags\">flex-start</label>&nbsp;多行集中在顶部。",
      "<label class=\"console-tags\">flex-end</label>&nbsp;多行集中在底部。",
      "<label class=\"console-tags\">center</label>&nbsp;多行居中。",
      "<label class=\"console-tags\">space-between</label>&nbsp;行与行之间保持相等距离。",
      "<label class=\"console-tags\">space-around</label>&nbsp;每一行的两端保持相等距离。",
      "<label class=\"console-tags\">stretch</label>&nbsp;每一行都被拉伸直至填满容器。",
      "注意：当只有一行的时候&nbsp;<label class=\"console-tags\">align-content</label>&nbsp;没有任何效果。"],
    container: ["flex-wrap:wrap;", "align-content:flex-start;"],
    carrot: ["#F9E784", "#F9E784", "#F9E784", "#F9E784", "#F9E784",
      "#F9E784", "#F9E784", "#F9E784", "#F9E784", "#F9E784",
      "#F9E784", "#F9E784", "#F9E784", "#F9E784", "#F9E784"],
    rabbit: ["#F9E784", "#F9E784", "#F9E784", "#F9E784", "#F9E784",
      "#F9E784", "#F9E784", "#F9E784", "#F9E784", "#F9E784",
      "#F9E784", "#F9E784", "#F9E784", "#F9E784", "#F9E784"],
    single: ["#", "#", "#", "#", "#",
      "#", "#", "#", "#", "#",
      "#", "#", "#", "#", "#"]
  },
  {
    desc: "现在FlexRabbit都逃窜到底部了。继续使用&nbsp;<label class=\"console-tags\">align-content</label>&nbsp;来捕获FlexRabbit。",
    tips: ["注意：请查看上一关的注意事项。"],
    container: ["flex-wrap:wrap;", "align-content:flex-end;"],
    carrot: ["#F9E784", "#F9E784", "#F9E784", "#F9E784", "#F9E784",
      "#F9E784", "#F9E784", "#F9E784", "#F9E784", "#F9E784",
      "#F9E784", "#F9E784", "#F9E784", "#F9E784", "#F9E784"],
    rabbit: ["#F9E784", "#F9E784", "#F9E784", "#F9E784", "#F9E784",
      "#F9E784", "#F9E784", "#F9E784", "#F9E784", "#F9E784",
      "#F9E784", "#F9E784", "#F9E784", "#F9E784", "#F9E784"],
    single: ["#", "#", "#", "#", "#",
      "#", "#", "#", "#", "#",
      "#", "#", "#", "#", "#"]
  },
  {
    desc: "现在FlexRabbit看起来很整齐，可以捕获了。可以使用&nbsp;<label class=\"console-tags\">flex-direction</label>&nbsp;和&nbsp;<label class=\"console-tags\">align-content</label>&nbsp;的组合，把FlexRabbit带回家。",
    tips: ["注意：请查看上一关的注意事项。"],
    container: ["flex-wrap:wrap;", "align-content:center;", "flex-direction:column-reverse;"],
    carrot: ["#ABE188", "#ABE188", "#ABE188",
      "#F9E784", "#F9E784", "#F9E784",
      "#F9E784", "#F9E784", "#F9E784",
      "#F9E784", "#F9E784", "#F9E784",
      "#F78E69", "#F78E69", "#F78E69"],
    rabbit: ["#ABE188", "#ABE188", "#ABE188",
      "#F9E784", "#F9E784", "#F9E784",
      "#F9E784", "#F9E784", "#F9E784",
      "#F9E784", "#F9E784", "#F9E784",
      "#F78E69", "#F78E69", "#F78E69"],
    single: ["#", "#", "#", "#", "#",
      "#", "#", "#", "#", "#",
      "#", "#", "#", "#", "#"]
  },
  {
    desc: "游戏到达尾声，用前面所学到的知识，最后一次捕获FlexRabbit！",
    tips: ["<label class=\"console-tags\">justify-content</label>",
      "<label class=\"console-tags\">align-items</label>",
      "<label class=\"console-tags\">flex-direction</label>",
      "<label class=\"console-tags\">order</label>",
      "<label class=\"console-tags\">align-self</label>",
      "<label class=\"console-tags\">flex-wrap</label>",
      "<label class=\"console-tags\">flex-flow</label>",
      "<label class=\"console-tags\">align-content</label>",],
    container: ["flex-direction:column-reverse;", "flex-wrap:wrap-reverse;", "justify-content:center;", "align-content:space-between;"],
    carrot: ["#F78E69",
      "#F9E784", "#F9E784", "#F9E784", "#F9E784",
      "#ABE188", "#ABE188"],
    rabbit: ["#F78E69",
      "#F9E784", "#F9E784", "#F9E784", "#F9E784",
      "#ABE188", "#ABE188"],
    single: ["#",
      "#", "#", "#", "#",
      "#", "#",]
  },
]

export default Checkpoint